apiversion: apps/v1
kind: Deployment
metadata:
    name: auth-mongo-depl
spec:
    replicas: 1
    selector:
        matchLabels: 
            app: auth-mongo
    template:
        metadata:
            labels:
                app: auth-mongo
        spec:
            contaners:
                - name: auth-mongo
                  image: mongo
---
apiversion: v1
kind: Service
metadata:
    name: auth-mongo-srv
sepc:
    selector:
        app: auth-mongo
    ports:
        - name: db
          protocol: TCP
          port: 27017
          targetPort: 27017